# Generated by Django 3.0.2 on 2021-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
